services:
  audiobook-organizer:
    image: ghcr.io/cruv/audiobook-organizer:latest
    container_name: AudiobookOrganizer
    ports:
      - "8081:80"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Indiana/Indianapolis
      - GOOGLE_BOOKS_API_KEY=
    volumes:
      - /home/cruv/DockerStorage/audiobookorganizer:/app/data
      - /path/to/audiobooks:/audiobooks
      - /path/to/organized:/organized
    restart: unless-stopped
